name: Get available action data

on:
  push:
    branches:
      - main

  schedule:
    - cron: 7 0 * * 1-5

  # run manually
  workflow_dispatch:

jobs:
  get-action-data:
    runs-on: ubuntu-latest

    steps:
    - uses: test-gha-market/load-available-actions@v2.1.3
      name: Load available actions
      id: load-actions
      with:
        PAT: ${{ secrets.PAT_GITHUB }}
        user: ${{ github.repository_owner }}

    - name: Update filename
      id: filename
      run: |
        filename="actions-data.json"
        mv ${{ steps.load-actions.outputs.actions-file-path }} $filename
        echo "filename=$filename" >> $GITHUB_OUTPUT

    - name: Upload result file as artefact
      uses: actions/upload-artifact@v3
      with:
        name: actions
        path: ${{ steps.filename.outputs.filename }}

    - name: Upload json to this repository
      # fork of LasyIsLazy/github-upload-action
      uses: test-gha-market/github-upload-action@v0.2.0
      with:
        access-token: ${{ secrets.PAT }}
        file-path: actions-data.json
        owner: ${{ github.repository_owner }}
        repo: actions-marketplace # ${{ github.repository }} doesn't work with this action :-(, it'll fail over the slash and owner name
        #remote-dir:  // upload in the root
        branch-name: gh-pages
